// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Reprocessing = require("/Users/shaddox/work/reason-dojo-01/reprocessing-example/node_modules/reprocessing/lib/js/src/Reprocessing.js");

Reprocessing.hotreload(undefined, "src/index.re");

/*  Not a pure module */
